### ISSUE TITLE
navbar-burger does not work after first clean installation

### ISSUE THREAD

**Issue by 10111DG** [v4iv/gatsby-starter-business#10]
My Steps:  

1) gatsby new mysitename https://github.com/v4iv/gatsby-starter-business.git
2) yarn start
3) open in Chrome  http://localhost:8000/
4) using developer tools simulating iPhone 6 navbar-burger does not react onclick and there are also no errors in the console

**Comment by 10111DG** [comment]
yarn version v1.12.3
npm version 6.4.1
node v8.11.1

**Comment by v4iv** [comment]
#11 Fixed Navbar Burger not working in development.
