### ISSUE TITLE
Change Colors and Styles

### ISSUE THREAD

**Issue by s1monw1** [v4iv/gatsby-starter-business#16]
I don't seem to be able to change the colors used in the default site. Where do I find the classes like `footer` and `container` used in the HTML?

**Comment by isif-ostewg** [comment]
> I don't seem to be able to change the colors used in the default site. Where do I find the classes like `footer` and `container` used in the HTML?

Are you able to advise how I would go about changing the burger menu element css?

**Comment by mmikeww** [comment]
What was the answer to this?
