### ISSUE TITLE
Refine Elasticlunr.js search

### ISSUE THREAD

**Issue by edemirbag** [v4iv/gatsby-starter-business#24]
**Current behaviour**: some page titles, e.g. the keywords "about" and "blog", are never matched.

**Desired behaviour**: widen/amend search to recognise currently unrecognised search terms such as "about".

Some potentially useful links:
- [https://github.com/weixsong/elasticlunr.js/issues/101](https://github.com/weixsong/elasticlunr.js/issues/101)
- [https://stackoverflow.com/questions/42220460/elasticlunr-js-not-showing-results-for-search-query](https://stackoverflow.com/questions/42220460/elasticlunr-js-not-showing-results-for-search-query)
- [https://gist.github.com/samdutton/7973dcff2c2c14ae28339148c7290a2f#file-index-js](https://gist.github.com/samdutton/7973dcff2c2c14ae28339148c7290a2f#file-index-js)

**Comment by v4iv** [comment]
Hey @edemirbag I did some digging and found out that this(ignoring/including stop words) is an issue/feature request with [gatsby-plugin-elasticlunr-search](https://github.com/gatsby-contrib/gatsby-plugin-elasticlunr-search) and this cannot be fixed from our side.
