### ISSUE TITLE
Issues deploying

### ISSUE THREAD

**Issue by apfranzen** [v4iv/gatsby-starter-business#6]
First off, thank you for the template, this has been really helpful. The content from the model and `.md` files is populating the website when `gatsby develop`, just not after building the static site. I deployed to netlify and I removed the editorial workflow. I am having issues with the following:

- After `gatsby build`, none of the content in the model (from the `.md` files) is able to viewed/edited in the `/admin/` view
- I am not able to add content of any type in `admin/` view. Upon attempting to publish, I get an error stating : `Failed to persist entry: TypeError: Cannot read property 'sha' of undefined`
- I am not able to upload pictures from view `/admin/`. The path in `config.yml` appears to be correct.

Could you please help me with these issues? I would really like to use your template.

**Comment by Vitalikda** [comment]
@apfranzen If you are using GitLab, it does not support Editorial Workflow ([yet](https://www.netlifycms.org/docs/configuration-options/#publish-mode)) and can lead to these issues. 

Comment the `publish_mode` in your Netlify CMS `config.yml` file:

``` 
# publish_mode: editorial_workflow
```

@v4iv thanks for the Starter!
